language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - CHAINER_VERSION=4.5.0     # the last release of chainer v4
  - CHAINER_VERSION=5.2.0
  - CHAINER_VERSION=6.0.0b2
install:
  - pip install chainer==$CHAINER_VERSION
  - pip install six==1.12.0
  - pip install texttable==1.6.0
  - pip install flake8==3.7.5
  - pip install pytest==4.2.1
  - pip install pytest-cov==2.6.1
  - pip install coveralls==1.5.1
script:
  - python -m pytest --cov chainer_computational_cost
  - flake8 .
  - cp DETAILS.md DETAILS_tmp.md
  - python make_details_md.py
  - diff DETAILS.md DETAILS_tmp.md  # check DETAILS.md is properly updated
after_success:
  - coveralls
